require "open_bd/version"
require "open_bd/client"
require "open_bd/content"
require "open_bd/contributor"
require "open_bd/paper"
require "open_bd/resource"
require "open_bd/response"
require "open_bd/title"
